// ============================================================
// fileless_reflection.fsx
// Carrega uma DLL a partir de uma string Base64 (fileless)
// e usa reflexão para listar tipos e invocar um método.
// ============================================================

open System
open System.Reflection
open System.Text

// ------------------------------------------------------------
// 1. Coloque aqui a sua DLL codificada em Base64.
//    Para gerar: Convert.ToBase64String(File.ReadAllBytes("minha.dll"))
// ------------------------------------------------------------
let dllBase64 = 
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAIqVYs4AAAAAAAAAAOAAIiALATAAAAoAAAAGAAAAAAAA0ikAAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAIApAABPAAAAAEAAADADAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAACQKAAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAA2AkAAAAgAAAACgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAADADAAAAQAAAAAQAAAAMAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAEAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAC0KQAAAAAAAEgAAAACAAUAwCAAANAHAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4CKA0AAAoqXgIoDQAACgIXjREAAAElFgOcfQEAAAQqOgIoDQAACgIDfQEAAAQqOgIoDQAACgIDfQIAAAQqXn4OAAAKcgEAAHByNQAAcBYoBQAABiYqRnJNAABwAnJZAABwKA8AAAoqHgIoEAAACipCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMxOQAAAAAFAGwAAAC0AgAAI34AACADAADoAgAAI1N0cmluZ3MAAAAACAYAAGAAAAAjVVMAaAYAABAAAAAjR1VJRAAAAHgGAABYAQAAI0Jsb2IAAAAAAAAAAgAAAVcVABQJAAAAAPoBMwAWAAABAAAAEwAAAAUAAAACAAAACAAAAAUAAAAQAAAAFAAAAAEAAAABAAAAAQAAAAEAAAAAAPEBAQAAAAAABgA9AWQCBgCoAWQCBgCFAFECDwCEAgAABgDCANABBgCPARMCBgAeARMCBgDbABMCBgD4ABMCBgBdARMCBgCrABMCBgBSAGQCBgC8AQwCBgC4AgwCBgBtAAwCBgDQAgwCBgDGAQwCBgBKAgwCBgDqAQwCAAAAAA0AAAAAAAEAAQAAARAAQAChAjUAAQABAAABEACZAGQCNQABAAIAAAEQAHYBZAI1AAIABAABABAANAAAAEEAAwAFACYAkwIuACYAywEyAFAgAAAAAIYYRAIGAAEAWCAAAAAAhhhEAjUAAQBwIAAAAACGGEQCOgABAH8gAAAAAIYYRAI1AAEAAAAAAIAAkSDcAkAAAQCOIAAAAACWADsCSAAFAKYgAAAAAJYALQJMAAUAuCAAAAAAhhhEAgYABgAAAAEAFgAAAAIA1wIAAAMAJQIAAAQALwAAAAEAKgAJAEQCAQARAEQCBgAZAEQCCgApAEQCEAAxAEQCEAA5AEQCEABBAEQCEABJAEQCEABRAEQCEABZAEQCEABhAEQCBgB5AEQCFQBpAEQCBgCRADYCGwCZAMkCHgCBAEQCBgAuAAsAUQAuABMAWgAuABsAeQAuACMAggAuACsAwAAuADMA0QAuADsA3gAuAEMA6wAuAEsAwAAuAFMAwABDAFsA9gBDAAoA9gBjAFsA9gBjAAoA9gBjAGMA+wCDAFsA9gCDAAoA9gCDAGMAIgGjACIASQGjABIATwEBAgQBCwDcAgEABIAAAAEAAAAAAAAAAAAAAAAAAQAAAAYAAAAAAAAAAAAAACUAGwAAAAAAAAAAAABDb25zb2xlQXBwMQA8TW9kdWxlPgBoV25kAFN5c3RlbS5SdW50aW1lAG5vbWUAdHlwZQBNaW5oYUNsYXNzZQBFbWJlZGRlZEF0dHJpYnV0ZQBDb21waWxlckdlbmVyYXRlZEF0dHJpYnV0ZQBBdHRyaWJ1dGVVc2FnZUF0dHJpYnV0ZQBEZWJ1Z2dhYmxlQXR0cmlidXRlAE51bGxhYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3b3JrQXR0cmlidXRlAEFzc2VtYmx5RmlsZVZlcnNpb25BdHRyaWJ1dGUAQXNzZW1ibHlJbmZvcm1hdGlvbmFsVmVyc2lvbkF0dHJpYnV0ZQBBc3NlbWJseUNvbmZpZ3VyYXRpb25BdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUATnVsbGFibGVDb250ZXh0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBCeXRlAEZsYWcAU3lzdGVtLlJ1bnRpbWUuVmVyc2lvbmluZwBTdHJpbmcAQ29uc29sZUFwcDEuZGxsAHVzZXIzMi5kbGwAU3lzdGVtAFN5c3RlbS5SZWZsZWN0aW9uAGNhcHRpb24AU2F1ZGFjYW8AWmVybwBFeGVjdXRhcgAuY3RvcgBJbnRQdHIAU3lzdGVtLkRpYWdub3N0aWNzAFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMARGVidWdnaW5nTW9kZXMATnVsbGFibGVGbGFncwBNaWNyb3NvZnQuQ29kZUFuYWx5c2lzAEF0dHJpYnV0ZVRhcmdldHMAQ29uY2F0AE9iamVjdAB0ZXh0AE1lc3NhZ2VCb3gAAAAzRQB4AGUAYwB1AHQAYQBkAG8AIAB2AGkAYQAgAFIAZQBmAGwAZQBjAHQAaQBvAG4AIQAAF0YAaQBsAGUAbABlAHMAcwAgAEYAIwAAC08AbADhACwAIAABAyEAAAAAAPkV0kbfvYpBgsO/zPZwt0MABCABAQgDIAABBSABARERBCABAQ4FIAEBETkCBhgGAAMODg4OCLA/X38R1Qo6AwYdBQIGBQQgAQEFBSABAR0FBwAECBgODgkDAAABBAABDg4IAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEAAgAAAAAAPQEAGC5ORVRDb3JlQXBwLFZlcnNpb249djYuMAEAVA4URnJhbWV3b3JrRGlzcGxheU5hbWUILk5FVCA2LjAQAQALQ29uc29sZUFwcDEAAAwBAAdSZWxlYXNlAAAMAQAHMS4wLjAuMAAACgEABTEuMC4wAAAEAQAAACYBAIRrAAACAFQCDUFsbG93TXVsdGlwbGUAVAIJSW5oZXJpdGVkACYBAEwUAAACAFQCDUFsbG93TXVsdGlwbGUAVAIJSW5oZXJpdGVkAAUBAAEAAAUBAAAAAAAAAAAAAAAczFiYAAFNUAIAAAB1AAAA5CgAAOQKAAAAAAAAAAAAAAEAAAATAAAAJwAAAFkpAABZCwAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAFJTRFORJnx+7oJnToumBC10H9nwAQAAAEM6XFVzZXJzXHppb3R0YWx1Y2FzXHNvdXJjZVxyZXBvc1xDb25zb2xlQXBwMVxDb25zb2xlQXBwMVxvYmpcUmVsZWFzZVxuZXQ2LjBcQ29uc29sZUFwcDEucGRiAFNIQTI1NgCRJnx+7oJnnsumBC10H9nwHMxYmM/AHZcheItQuXxdKqgpAAAAAAAAAAAAAMIpAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0KQAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABAAAAAYAACAAAAAAAAAAAAAAAAAAAABAAEAAAAwAACAAAAAAAAAAAAAAAAAAAABAAAAAABIAAAAWEAAANQCAAAAAAAAAAAAANQCNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAQAAAAAAAAABAAAAAAA/AAAAAAAAAAQAAAACAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsAQ0AgAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAAAQAgAAAQAwADAAMAAwADAANABiADAAAAA4AAwAAQBDAG8AbQBwAGEAbgB5AE4AYQBtAGUAAAAAAEMAbwBuAHMAbwBsAGUAQQBwAHAAMQAAAEAADAABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABDAG8AbgBzAG8AbABlAEEAcABwADEAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADEALgAwAC4AMAAuADAAAABAABAAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEMAbwBuAHMAbwBsAGUAQQBwAHAAMQAuAGQAbABsAAAAKAACAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAIAAAAEgAEAABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABDAG8AbgBzAG8AbABlAEEAcABwADEALgBkAGwAbAAAADgADAABAFAAcgBvAGQAdQBjAHQATgBhAG0AZQAAAAAAQwBvAG4AcwBvAGwAZQBBAHAAcAAxAAAAMAAGAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAA1DkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

// ------------------------------------------------------------
// 2. Decodifica e carrega o assembly em memória
// ------------------------------------------------------------
let assemblyBytes = Convert.FromBase64String(dllBase64)
let assembly = Assembly.Load(assemblyBytes)

printfn "Assembly carregado: %s" assembly.FullName

// ------------------------------------------------------------
// 3. Usa reflexão para listar todos os tipos públicos
// ------------------------------------------------------------
let tipos = assembly.GetExportedTypes()
printfn "\nTipos públicos encontrados:"
for t in tipos do
    printfn "  - %s" t.FullName

// ------------------------------------------------------------
// 4. Exemplo: localiza um tipo e invoca um método estático
//    (ajuste os nomes conforme sua DLL)
// ------------------------------------------------------------
let tipoAlvo = 
    tipos |> Array.tryFind (fun t -> t.Name = "MinhaClasse")  // substitua

match tipoAlvo with
| None -> printfn "\nTipo 'MinhaClasse' não encontrado."
| Some t ->
    printfn "\nTipo encontrado: %s" t.FullName

    // Lista métodos públicos (estáticos e de instância)
    let metodos = t.GetMethods(BindingFlags.Public ||| BindingFlags.Static ||| BindingFlags.Instance)
    printfn "Métodos:"
    for m in metodos do
        printfn "  - %s" m.Name

    // Tenta invocar um método estático chamado "Executar" (sem parâmetros)
    let metodo = t.GetMethod("Executar", BindingFlags.Public ||| BindingFlags.Static)
    match metodo with
    | null -> printfn "\nMétodo estático 'Executar' não encontrado."
    | m ->
        try
            let resultado = m.Invoke(null, null)  // null para estático, sem args
            printfn "\nResultado da invocação: %A" resultado
        with ex ->
            printfn "\nErro ao invocar: %s" ex.Message

    // Se quiser criar uma instância e invocar método de instância:
    // let instancia = Activator.CreateInstance(t)
    // let metodoInst = t.GetMethod("MetodoInstancia")
    // metodoInst.Invoke(instancia, [| |]) |> ignore

printfn "\nConcluído."
